"""
Libby-assisted workflow routes for Story Forge.
"""

from __future__ import annotations

import asyncio
import json

from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel

from ai_providers import ai_provider_manager
from context_engine import build_runtime_context_packet
from db_helpers import get_book_by_id, get_chapters_for_book
from style_studio import build_style_context
from .auth_utils import require_auth

router = APIRouter()


class NextChapterIdeasRequest(BaseModel):
    refresh: bool = True


class NextChapterGenerateRequest(BaseModel):
    direction: str
    chapter_title: str | None = None


class GeneratedChapterDraftResponse(BaseModel):
    title: str
    content: str
    order: int


def _build_story_context(book_id: int) -> dict:
    book = get_book_by_id(book_id)
    if not book:
        raise HTTPException(status_code=404, detail="Book not found")

    chapters = get_chapters_for_book(book_id)
    runtime_context = build_runtime_context_packet(book_id)
    recent_chapters = chapters[-3:]
    return {
        "book": {
            "id": book.id,
            "title": book.title,
            "author": book.author,
            "description": book.description,
            "status": book.status.value if hasattr(book.status, "value") else str(book.status),
        },
        "context_summary": runtime_context,
        "style_studio": build_style_context(book_id),
        "recent_chapters": [
            {
                "id": chapter.id,
                "title": chapter.title,
                "order": chapter.order,
                "word_count": chapter.word_count,
                "excerpt": (chapter.content or "")[:2500],
            }
            for chapter in recent_chapters
        ],
        "chapter_count": len(chapters),
    }


def _extract_json_dict(value) -> dict | None:
    if isinstance(value, dict):
        return value
    if isinstance(value, str):
        stripped = value.strip()
        if stripped.startswith("{") and stripped.endswith("}"):
            try:
                parsed = json.loads(stripped)
            except json.JSONDecodeError:
                return None
            if isinstance(parsed, dict):
                return parsed
    return None


def _extract_json_list(value) -> list | None:
    if isinstance(value, list):
        return value
    if isinstance(value, str):
        stripped = value.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            try:
                parsed = json.loads(stripped)
            except json.JSONDecodeError:
                return None
            if isinstance(parsed, list):
                return parsed
    return None


def _normalize_idea(idea, idx: int) -> dict | None:
    if isinstance(idea, str):
        text = idea.strip()
        if not text:
            return None
        return {
            "id": f"idea-{idx}",
            "title": f"Scenario {idx}",
            "direction": text,
            "rationale": "Generated by Libby from current story context.",
        }
    if isinstance(idea, dict):
        direction = str(idea.get("direction") or idea.get("prompt") or "").strip()
        if not direction:
            return None
        title = str(idea.get("title") or f"Scenario {idx}").strip()
        rationale = str(idea.get("rationale") or idea.get("why") or "").strip()
        return {
            "id": str(idea.get("id") or f"idea-{idx}"),
            "title": title,
            "direction": direction,
            "rationale": rationale or "Generated by Libby from current story context.",
        }
    return None


def _parse_ideas_response(response: dict) -> list[dict]:
    candidates: list | None = None
    for key in ("ideas", "scenarios", "options"):
        candidates = _extract_json_list(response.get(key))
        if candidates is not None:
            break

    if candidates is None:
        for key in ("result", "output", "data"):
            payload = _extract_json_dict(response.get(key))
            if payload:
                for nested_key in ("ideas", "scenarios", "options"):
                    candidates = _extract_json_list(payload.get(nested_key))
                    if candidates is not None:
                        break
            if candidates is not None:
                break

    if candidates is None:
        raise HTTPException(status_code=502, detail="Libby did not return usable next-chapter ideas.")

    ideas: list[dict] = []
    for idx, idea in enumerate(candidates[:3], start=1):
        normalized = _normalize_idea(idea, idx)
        if normalized:
            ideas.append(normalized)

    if not ideas:
        raise HTTPException(status_code=502, detail="Libby returned empty next-chapter ideas.")
    return ideas[:3]


def _sanitize_generated_text(value: str) -> str:
    sanitized = value.replace("---", "\n\n").replace("—", ", ")
    while "\n\n\n" in sanitized:
        sanitized = sanitized.replace("\n\n\n", "\n\n")
    while "  " in sanitized:
        sanitized = sanitized.replace("  ", " ")
    return sanitized.strip()


def _parse_generated_chapter(response: dict) -> dict:
    for key in ("chapter", "result", "output", "data"):
        payload = response.get(key)
        if isinstance(payload, dict):
            title = str(payload.get("chapter_title") or payload.get("title") or "").strip()
            content = str(payload.get("chapter_content") or payload.get("content") or "").strip()
            if content:
                return {"title": title, "content": _sanitize_generated_text(content)}
        if isinstance(payload, str):
            stripped = payload.strip()
            if stripped.startswith("{") and stripped.endswith("}"):
                try:
                    parsed = json.loads(stripped)
                except json.JSONDecodeError:
                    parsed = None
                if isinstance(parsed, dict):
                    title = str(parsed.get("chapter_title") or parsed.get("title") or "").strip()
                    content = str(parsed.get("chapter_content") or parsed.get("content") or "").strip()
                    if content:
                        return {"title": title, "content": _sanitize_generated_text(content)}

    content = str(response.get("chapter_content") or response.get("content") or "").strip()
    title = str(response.get("chapter_title") or response.get("title") or "").strip()
    if content:
        return {"title": title, "content": _sanitize_generated_text(content)}

    raise HTTPException(status_code=502, detail="Libby did not return usable chapter content.")


@router.post("/books/{book_id}/next-chapter/ideas")
def next_chapter_ideas(request: Request, book_id: int, _: NextChapterIdeasRequest):
    require_auth(request)
    story_context = _build_story_context(book_id)
    response = asyncio.run(
        ai_provider_manager.suggest_next_chapter_ideas(
            story_context=story_context,
            chapter_count=story_context["chapter_count"],
            current_book_title=story_context["book"]["title"],
        )
    )
    if not response.get("success"):
        raise HTTPException(status_code=503, detail=response.get("error") or "Libby is unavailable.")

    return {
        "ideas": _parse_ideas_response(response),
        "chapter_count": story_context["chapter_count"],
    }


@router.post("/books/{book_id}/next-chapter/generate", response_model=GeneratedChapterDraftResponse)
def generate_next_chapter(request: Request, book_id: int, body: NextChapterGenerateRequest):
    require_auth(request)

    direction = body.direction.strip()
    if not direction:
        raise HTTPException(status_code=400, detail="A story direction is required.")

    story_context = _build_story_context(book_id)
    next_order = story_context["chapter_count"] + 1
    fallback_title = body.chapter_title.strip() if body.chapter_title else f"Chapter {next_order}"

    response = asyncio.run(
        ai_provider_manager.submit_story_direction(
            story_direction=direction,
            story_context=story_context,
            chapter_title=fallback_title,
        )
    )
    if not response.get("success"):
        raise HTTPException(status_code=503, detail=response.get("error") or "Libby is unavailable.")

    generated = _parse_generated_chapter(response)
    return GeneratedChapterDraftResponse(
        title=generated["title"] or fallback_title,
        content=generated["content"],
        order=next_order,
    )
